### PR TITLE
(more) fixes in ubuntu.sh

### PR DESCRIPTION
**Pull request by zrhmn**
I'm terribly sorry for coming in with very small changes. I'm executing the scripts one by one on a Vagrant machine running Debian Jessie and when encountering issues, fixing the issues and then coming back here to propose the changes. It looks like I'm making new pull requests for minute changes for kicks. It's just that I haven't got git set up on the Vagrant machine where I'm doing the fixing-upping so I can't commit and push all the changes at once from there. Therefore for every small change I make in the script, I have to come here to GitHub and make and propose the changes online using the GitHub editor so that I don't forget how I got it to work. Sorry again.

See commit message 18e5123 for details of this pull request.

### CODE REVIEW

**Comment by hudecof** [comment]
Hi,

small changes are better ten big one ;)

**Comment by hudecof** [comment]
I haven't used these script for a long time so thaks for fixing them.

**Comment by zrhmn** [comment]
Well I finished with your blog post (and by extension, this repo) but my problem didn't get resolved.

I wanted to make apt-cacher-ng cache packages for CentOS servers as well. But the problem is that `yum` inside my CentOS server would not `update` when using the apt-cacher-ng server as `proxy` inside `/etc/yum.conf`. And I haven't found any alternatives either.

**Comment by hudecof** [comment]
Last time I tried to use apt-cacher-ng for CentOS it doesn't work out of the box. The Redhat based repositories have different structure, so some configuration tweaking is needed.
Generally my issues with the CentOS was
1) mirrorlist is not working. Try to use specific mirror
2) https connection needs to be specified in PassThroughPattern and the packages are not cached. There is a small workaround how to cache  HTTPS using remap, but it could not be used generally.

**Comment by zrhmn** [comment]
Well I know nothing about the yum ecosystem. I've only just recently had to work with CentOS. A huge part of why I preferred Ubuntu or any Debian based distribution was that I understood apt better.

I have heard good things about [mrepo](http://dag.wiee.rs/home-made/mrepo/) and also [pulp](http://www.pulpproject.org/) is listed as the first option in the [relevant page](http://yum.baseurl.org/wiki/YumMultipleMachineCaching) on yum wiki. However I have yet to try any of those out.

The thing is, if you have a cluster with both Debian and RHEL based machines, an optimum solution would serve cached packages for both apt and yum. Having to run different services (apt-cacher-ng _and_ mrepo etc.) on the same machine while knowing that it could potentially have been done well enough with just one of them is what would make a sysadmin lose sleep.

I'm gonna have to go deeper into it, just as soon as I find time and patience.

**Comment by hudecof** [comment]
So do I, more then 95% of distro is Debian based. I was using apt-cacher-ng for debian and it was only access to the outside world for the machines. ;(
I have to go deeply how the yum works and understand where is the problem. On the other hand, I'm paying with option to have private mirror for both.

**Pull request merged**
